[package]
name = "fastLink"
version = "0.9.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.38", features = ["derive"] }
dunce = "1.0.5"
env_logger = { version = "0.11.8" }
lazy_static = "1.5.0"
log = "0.4.27"
path-clean = "1.0.1"
regex = "1.11.1"
strip-ansi-escapes = "0.2.1"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.20.0"
