[package]
name = "fastLink"
version = "0.4.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.37", features = ["derive"] }
dunce = "1.0.5"
env_logger = { version = "0.11.8" }
log = "0.4.27"
path-clean = "1.0.1"
